DROP TABLE MLT CASCADE CONSTRAINTS;
DROP TABLE NURSE CASCADE CONSTRAINTS;
DROP TABLE DOCTOR CASCADE CONSTRAINTS;
DROP TABLE PATIENT_INFO_RECORD CASCADE CONSTRAINTS;
DROP TABLE SURGERY_RECORD;
DROP TABLE LABORATORY_RECORD;
DROP TABLE MEDICINE_RECORD;
DROP TABLE FINANCE_RECORD;
